#pragma once

#include <list>
#include "RenderOperation.h"

namespace Apoc3D
{
	namespace Core
	{
		/*
		  A buffer to store list of RenderOperation.
		  RenderOperation generated by Renderable objects 
		  should be add into this buffer before passing to the rendering engine.
		*/
		class _Export RenderOperationBuffer
		{
		private:
			RenderOperation* oplist;

			void Resize(int size)
			{

			}

		public:
			RenderOperationBuffer(void)
			{

			}
			~RenderOperationBuffer(void)
			{

			}

			void Add(const RenderOperation& op)
			{
				//oplist.push_back(op);
			}
			void Add(RenderOperation* op, int count)
			{

			}

			void Clear(){ }

			RenderOperation get(int i)
			{

			}

			int getCount(){}
		};

	}
}