
#ifndef APB_ERRORCODE_H
#define APB_ERRORCODE_H

#define ERR_CONFIG_FILE_NOT_FOUND 16000
#define ERR_UNSUPPORTED_BUILD 16001
#define ERR_THERE_ARE_WARNINGS 16002
#define ERR_THERE_ARE_ERRORS 16003

#endif